name: E2E Testing

on:
  repository_dispatch:
    types: [ahadev-sync-success]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui-test:
    name: UI test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile --non-interactive

      - name: Run tests
        run: yarn cy-test

  ui-test-failure-notification:
    name: UI test failure notification
    runs-on: ubuntu-latest

    if: ${{ always() && needs.ui-test.result == 'failure' }}
    needs: [ui-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mandrillapp.com
          server_port: 465
          username: Aha-Actions-Bot
          password: jZCfo1jeJEAqV8ps7myugw
          subject: ${{github.repository}} - UI Test Failure - Github Actions
          to: thaintp@dgroup.co
          from: Aha-Actions-Bot <aha-actions-bot@dgroup.co>
          body:
            ${{github.repository}} - UI Test Failed
