name: CI deploy

on:
  repository_dispatch:
    types: [argocd-sync-success]

jobs:
  update-image:
    name: "Auto deploy"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
